import json
import textwrap

with open('.release-please-manifest.json') as f:
    f = json.load(f)
    a = textwrap.dedent(f"""
    # Generated by build pipeline
    module_one   = {f.get('modules/module-one')}
    module_two   = {f.get('modules/module-two')}
    module_three = {f.get('modules/module-three')}
    """).strip()
    with open(".auto.tfvars", "w") as tfvars:
        tfvars.write(a)
