import json
import textwrap

with open('.release-please-manifest.json') as f:
    f = json.load(f)
    a = textwrap.dedent(f"""
    # Generated by build pipeline
    module_one   = "{f.get('modules/module-one')}"
    module_two   = "{f.get('modules/module-two')}"
    """).strip()
    with open("tf/terraform.tfvars", "w") as tfvars:
        tfvars.write(a)
