on:
  push:
    branches:
      - "**"

name: branch

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world" > test.txt
          echo "${{ hashFiles('**') }}"

      - env:
          HASH: ${{ hashFiles('**') }}
        run: |
          echo "Hash: $HASH"
