on:
  push:
    branches:
      - "**"

name: branch

jobs:
  hash:
    runs-on: ubuntu-latest
    outputs:
      artifact-hash: ${{ steps.hash.outputs.hash }}

    steps:
      - run: |
          echo "hello world" > test.txt
          cat test.txt
          echo "${{ hashFiles('test.txt') }}"

      - id: hash
        run: |
          cat test.txt
          echo "hash=${{ hashFiles('test.txt') }}" | tee -a $GITHUB_OUTPUT

      - env:
          HASH: ${{ hashFiles('test.txt') }}
        run: |
          echo "Hash: $HASH"

  read:
    runs-on: ubuntu-latest
    needs: hash

    steps:
      - if: ${{ hashFiles('test.txt') != needs.hash.outputs.artifact-hash }}
        run: |
          echo "Hashes didn't match ${{ hashFiles('test.txt') }} != ${{ needs.hash.outputs.artifact-hash }}
          exit 1

      - run: |
          echo "hash: ${{ needs.hash.outputs.artifact-hash }}"