on:
  push:
#    tags:
#      - '*'
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: branch and pr

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /rate_limit
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: create & push branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b something-to-main
          sed -i 's/version/0.3.0/g' tf/main.tf
          git add tf/main.tf
          git commit -m "This is a test"
          git push origin something-to-main

      - name: create pull request
        run: gh pr create -B main -H something-to-main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ github.token }}
