on:
  push:
    tags:
      - '*'
#      - 'v[0-9]+.[0-9]+.[0-9]+'
#    branches:
#      - main

permissions:
  contents: write
  pull-requests: write

name: branch and pr

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /rate_limit
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: create & push branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b deploy-${{ github.ref_name }}-to-stg
          sed -i 's/version/${{ github.ref_name }}/g' tf/main.tf
          git add tf/main.tf
          git commit -m "chore(main): Deploy ${{ github.ref_name }} to stg"
          git push origin deploy-${{ github.ref_name }}-to-stg

      - name: create pull request
        run: |
          PR=`gh pr create -B main -H deploy-${{ github.ref_name }}-to-stg --title 'Deploy ${{ github.ref_name }} to stg' --body 'Created by Github action'`
          echo "PR=$PR"
          #gh pr merge --auto -s $PR
          gh pr merge -s $PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
