on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: branch and pr

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /rate_limit
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: create & push branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b something-to-main
          touch test-update
          git add test-update
          git commit -m "This is a test"
          git push origin something-to-main

      # create PR