on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this file will deploy" > deploy-me.plan
      - run: |
          echo "This is what i want to do:" | tee -a $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat deploy-me.plan | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: deploy-plan
          path: deploy-me.plan


  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: plan
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-plan
      - run: echo "Deploying!!" | tee -a $GITHUB_STEP_SUMMARY
      - run: echo "This is the file to deploy:" | tee -a $GITHUB_STEP_SUMMARY
      - run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat deploy-me.plan | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
