on:
  pull_request:
    branches:
      - main

name: pr-checks

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing the build"
          gh pr merge --auto -rs https://github.com/traksharp/some-actions/pull/27
