name: Validation

on:
  push:
    branches:
      # - '*' # matches every branch that doesn't contain a '/'
      # - '*/*' # matches every branch containing a single '/'
      - '**' # matches every branch
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-syntax-check:
    runs-on: python:3.9
    steps:
      - run: pip install -Ur requirements-build.txt
      - run: pip install -Ur requirements.txt
      - run: ansible-playbook -i ./hosts ./test/ansible.yml -vv --syntax-check
