name: some / varied / action

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -Ur requirements-build.txt
      - run: pip install -Ur requirements.txt
      - run: ansible-playbook -i ./hosts ./test/ansible.yml -vv --syntax-check
